services:
  - type: web
    name: api-rate-limiter-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-rate-limiter-redis
          property: connectionString
      - key: CORS_ORIGIN
        sync: false

  - type: redis
    name: api-rate-limiter-redis
    plan: free
    maxmemoryPolicy: noeviction
